### ISSUE TITLE
FR: please co-publish on Open VSX Registry

### ISSUE THREAD

**Issue by GitMensch** [AdamAnandUS/AdamsTool#4]
The [Open VSX Registry](https://open-vsx.org/?search=toolbar) does not include a single toolbar extension yet and this one seems to be quite useful.

Details on the publishing can be found at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions you may publish this extension with a single command, `npx ovsx publish` (no need to install any dependency)

**Comment by AdamAnandUS** [comment]
This is a good idea. Let me check this out and update.

**Comment by GitMensch** [comment]
Friendly ping - any update on this?

**Comment by AdamAnandUS** [comment]
Hi Simon,

Thank you for checking on this.

Since I have not published here (Open VSX Registry) before, I need to learn how to do this.

Will figure it out and update you.

Cheers
Adam

________________________________

**Comment by AdamAnandUS** [comment]
> Friendly ping - any update on this?

I tried to publish and I got this error.

**'This extension cannot be accepted because it has no license.'**

I am not sure on how to proceed from here. Any help is sincerely appreciated.

Thanks
Adam

**Comment by AdamAnandUS** [comment]
> Friendly ping - any update on this?

It's published.

[https://open-vsx.org/extension/AdamAnand/adamstool](https://open-vsx.org/extension/AdamAnand/adamstool)

**Comment by GitMensch** [comment]
Thank you. We now have 0.17 there, but the source code is still at 0.16?

**Comment by AdamAnandUS** [comment]
It's updated.
